jobs:
  deploy:
    parallelism: 1
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - run:
          command: |
            sls deploy
  newman-collection-run:
    parallelism: 1
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./SimpleTests.json
orbs:
  newman: postman/newman@0.0.2
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1
workflows:
  version: 2
  workflow:
    jobs:
      - deploy
      - newman-collection-run