# Remember to make them execute sequentially
# and rewrite testing suite for proper url when it runs
# added something to commit

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: './Simple-Tests.json'
          environment: './simple-env.postman_environment.json'
          folder: 'User Interaction'
orbs:
  newman: postman/newman@0.0.2
version: 2.1
workflows:
  version: 2
  workflow:
    jobs:
      - newman-collection-run
