# Remember to make them execute sequentially
# and rewrite testing suite for proper url when it runs
# added something to commit

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - run:
          command: |
            sls deploy
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          command:
          sls info > output.txt
          (awk '/ANY - / {print $3}' output.txt' | head -1) > url.txt


      - newman/newman-run:
          collection: './Simple-Tests.json'
          environment: './simple-env.postman_environment.json'
          folder: 'User Interaction'
orbs:
  newman: postman/newman@0.0.2
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1
workflows:
  version: 2
  workflow:
    jobs:
      - deploy
      - newman-collection-run:
          requires:
            - deploy
